# Server-Port (Standard: 8080)
server.port=8080

# Anwendungsname
spring.application.name=OrchestrArchive

# JSON hübsch formatiert ausgeben (nur für Entwicklung)
spring.jackson.serialization.indent-output=true

# H2-Datenbank (in-file)
spring.datasource.url=jdbc:h2:file:/tmp/orchestrachive
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2-Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha